### ISSUE TITLE
Some questions about the mod and solder points

### ISSUE THREAD

**Issue by DarthMotzkus** [L10N37/Atmega-N64-IGR-#1]
Hi, how are you?
Great mod, want to try it. Been using the ps1 igr you've made, flawlessly so far. 
But i really appreciate if you can provide more pictures of this IGR N64 MOD, from wires and solder points on the n64 mb indicating the location of them and the targets on atmega board.
Question: Is 5V or VIN the correct point to solder on atmega arduino board? Seems they are equal, but some indicates 5V and you indicates VIN...
And one last question: Should i paste the 3 code files into Arduino IDE or just the .ino file?
Thank you in advance!

**Comment by L10N37** [comment]
Sorry for such a lazy response here ...for power you can find it with a multimeter, same goes with ground.

The reset line is part of kits like Etim NES RGB and N64 digital / pixelfx, originally you ran wires on V1 N64 digital mods and the solder pad on the flex is labelled 'reset', you could use these install photos as a reference. The later revisions with the buffer/ flex also grabs power from the same IC, so that's another reference, else, maybe there's a proper pinout for that IC online?

I don't have photos of my installation or anything and most of my stuff is either boxed or interstate. 

The guide I've provided is how I figured it out. You could probably power it from a 5v point as well if you run it through the correct pin that puts the 5v through the MCU's 3.3v LDO. 

This is easy to find with the power off as the 5v regulator is mounted to the main board and not straight from the powerpack, continuity mode from 5v regs output and you find alternate points.

The ino should be all you need to load, I'm pretty sure this will automatically open the cpp file too? I can't really remember, it's been ages. LMK how you go, enjoy.

To note: I wanted a different IGR combo, but the existing code utilised wasn't allowing me to read those buttons simultaneously. I simply an chose an alternate 'impossible to  accidentally press' combo.

**Comment by DarthMotzkus** [comment]
Thanks, and about arduino 5V and VIN:
Is 5V or VIN the correct point to solder on atmega arduino board? Seems they are equal, but some indicates 5V and you indicates VIN...

**Comment by L10N37** [comment]
I am pretty sure Voltage In and 5v would have 5v on it, but the MCU would be running off 3.3v which is the logicl level of the N64 comms line.

Again, a multimeter on continuity. VIN should run into the 3.3v LDO's input leg.
